---
abstract: 'Search for CPAN distributions by cpanid or distribution name'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-SmokeBox-Dists
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  POE::Component::SmokeBox::Dists:
    file: lib/POE/Component/SmokeBox/Dists.pm
    version: 1.04
requires:
  CPAN::DistnameInfo: 0.06
  File::Fetch: 0
  File::Path: 0
  File::Spec: 0
  IO::Zlib: 0
  POE: 1.004
  Sort::Versions: 1.5
  URI: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-component-smokebox-dists/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-smokebox-dists.git
version: 1.04
